### ISSUE TITLE
Test fails after build

### ISSUE THREAD

**Issue by xkill-9** [bjornharrtell/jsts#204]
I'm trying to run the test after building but i keep getting the same error 

```
iMac-de-user:jsts-master user$ npm test

> jsts@0.17.0 test /Users/user/Downloads/jsts-master
> mocha --recursive test/spec/ -r ./ -r test/init.js

/Users/user/Downloads/jsts-master/lib/jsts.js:768
this.distanceTolerance=distanceTolerance;};jsts.densify.Densifier.prototype.getResultGeometry=function(){return(new jsts.densify.Densifier.DensifyTransformer(this.distanceTolerance)).transform(this.geom);};jsts.densify.Densifier.DensifyTransformer=function(distanceTolerance){jsts.geom.util.GeometryTransformer.call(this);this.distanceTolerance=distanceTolerance;};jsts.densify.Densifier.DensifyTransformer.prototype=new jsts.geom.util.GeometryTransformer();jsts.densify.Densifier.DensifyTransformer.constructor=jsts.densify.Densifier.DensifyTransformer;jsts.densify.Densifier.DensifyTransformer.CLASS_NAME='jsts.densify.Densifier.DensifyTransformer';jsts.densify.Densifier.DensifyTransformer.prototype.transformCoordinates=function(coords,parent){var inputPts=coords;if(!(inputPts instanceof Array)){inputPts=coords.toCoordinateArray()};var newPts=jsts.densify.Densifier.densifyPoints(inputPts,this.distanceTolerance,parent.getPrecisionModel());if(parent inst

TypeError: jsts.geom.util.GeometryTransformer is not a function
    at /Users/user/Downloads/jsts-master/lib/jsts.js:768:418
    at Object.<anonymous> (/Users/user/Downloads/jsts-master/lib/jsts.js:770:466)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/user/Downloads/jsts-master/index.js:2:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/user/Downloads/jsts-master/node_modules/mocha/bin/_mocha:308:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/user/Downloads/jsts-master/node_modules/mocha/bin/_mocha:307:10)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by bjornharrtell** [comment]
Works for me and Travis.
