### ISSUE TITLE
GeoJSONWriter throws error when trying to write certain geometries

### ISSUE THREAD

**Issue by evansiroky** [bjornharrtell/jsts#268]
Here is an example:

```javascript
var jsts = require('jsts')

var geoJsonReader = new jsts.io.GeoJSONReader(),
  geoJsonWriter = new jsts.io.GeoJSONWriter()

var gjA = { 
  type: "MultiPolygon",
  coordinates: [
    [
      [
        [
          98.17728767261508,
          28.17246370445825
        ],
        [
          93.07752990722656,
          45.0162239074707
        ],
        [
          93.10541534423828,
          45.00222396850586
        ],
        [
          93.11858367919922,
          45.0006103515625
        ],
        [
          93.12930297851562,
          45
        ],
        [
          93.13925170898438,
          45
        ],
        [
          93.14794158935547,
          45.000999450683594
        ],
        [
          93.15666961669922,
          45.0033073425293
        ],
        [
          93.17333221435547,
          45.00763702392578
        ],
        [
          98.17728767261508,
          28.17246370445825
        ]
      ]
    ]
  ]
}

var gjB = {
  type: "Polygon",
  coordinates: [
    [
      [
        90,
        45
      ],
      [
        90,
        67.5
      ],
      [
        135,
        67.5
      ],
      [
        135,
        45
      ],
      [
        90,
        45
      ]
    ]
  ]
}

var _a = geoJsonReader.read(JSON.stringify(gjA)),
  _b = geoJsonReader.read(JSON.stringify(gjB))

var result = jsts.operation.overlay.OverlayOp.intersection(_a, _b)

result = geoJsonWriter.write(result)  // throws error
```

I'm getting this error:
```
TypeError: Cannot read property 'apply' of undefined
    at bi.Eo.GeometryCollection (...node_modules\jsts\dist\jsts.min.js:15:4355)
    at bi.e.write (...node_modules\jsts\dist\jsts.min.js:15:1281)
    at _i.e.write (...node_modules\jsts\dist\jsts.min.js:15:4904)
    at Object.<anonymous> (temp.js:89:24)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
```

**Comment by bjornharrtell** [comment]
Thanks for the report. Seems handling of GeometryCollection was incorrect, should be fixed now.

**Comment by evansiroky** [comment]
Confirmed fixed.  Thanks!
