### ISSUE TITLE
Add a non uglified build as "main" in package.json

### ISSUE THREAD

**Issue by Calvein** [bjornharrtell/jsts#269]
I'm having an error in a lib that uses jsts and the outputted error isn't very friendly.
```
/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/node_modules/jsts/dist/jsts.min.js:15
var t=new I;return this.root.addAllItems(t),t},remove:function(t,e){var n=Pi.ensureExtent(t,this.minExtent);return this.root.remove(n,e)},collectStats:function(t){var e=t.getWidth();e<this.minExtent&&e>0&&(this.minExtent=e);var n=t.getHeight();n<this.minExtent&&n>0&&(this.minExtent=n)},depth:function(){return null!==this.root?this.root.depth():0},isEmpty:function(){return null===this.root},interfaces_:function(){return[Fe,u]},getClass:function(){return Pi}}),Pi.ensureExtent=function(t,e){var n=t.getMinX(),i=t.getMaxX(),r=t.getMinY(),s=t.getMaxY();return n!==i&&r!==s?t:(n===i&&(n-=e/2,i=n+e/2),r===s&&(r-=e/2,s=r+e/2),new C(n,i,r,s))},Pi.serialVersionUID=-0x678b60c967a25400;var po=Object.freeze({Quadtree:Pi}),vo=Object.freeze({STRtree:ke}),mo=Object.freeze({quadtree:po,strtree:vo}),yo=["Point","MultiPoint","LineString","MultiLineString","Polygon","MultiPolygon"];e(bi.prototype,{read:function(t){var e=vo

TypeError: Cannot read property 'apply' of undefined
    at bi.Eo.GeometryCollection (/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/node_modules/jsts/dist/jsts.min.js:15:4336)
    at bi.e.write (/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/node_modules/jsts/dist/jsts.min.js:15:1281)
    at _i.e.write (/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/node_modules/jsts/dist/jsts.min.js:15:4885)
    at Object.intersect (/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/node_modules/turf-intersect/index.js:77:34)
    at /home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/data/format-geo.js:61:31
    at Array.forEach (native)
    at /home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/data/format-geo.js:59:12
    at Array.forEach (native)
    at Object.<anonymous> (/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/data/format-geo.js:52:2)
    at Module._compile (module.js:397:26)
```

I then removed `| uglifyjs -c -m --screw-ie8` from the `build` npm script and the error was a lot better:
```
/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/node_modules/jsts/dist/jsts.js:16917
        array.push(extract$1[type].apply(this, [geometry]));
                                  ^

TypeError: Cannot read property 'apply' of undefined
    at GeoJSONParser.GeometryCollection (/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/node_modules/jsts/dist/jsts.js:16917:35)
    at GeoJSONParser.write (/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/node_modules/jsts/dist/jsts.js:16561:30)
    at GeoJSONWriter.write (/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/node_modules/jsts/dist/jsts.js:17014:26)
    at Object.intersect (/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/node_modules/turf-intersect/index.js:77:34)
    at /home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/data/format-geo.js:61:31
    at Array.forEach (native)
    at /home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/data/format-geo.js:59:12
    at Array.forEach (native)
    at Object.<anonymous> (/home/donnees/workspaces/.smallmultiple/yvw/yvw-hardship-map/frontend/data/format-geo.js:52:2)
    at Module._compile (module.js:397:26)
```

**Comment by bjornharrtell** [comment]
In a near future Node JS will support modules and ES6 syntax, so it will be able to run the source as is. Until then, local builds will have to do.
