### ISSUE TITLE
TypeError: this.seg.p1.equals2D is not a function

### ISSUE THREAD

**Issue by andrewharvey** [bjornharrtell/jsts#276]
I'm running into this issue below, sample program and data is at https://gist.github.com/andrewharvey/113d277ce9847cbc73251a2e59314364

```
> ./index.js 
node_modules/jsts/dist/jsts.min.js:14
this.resultGeom=this.computeGeometry(this.resultPointList,this.resultLineList,this.resultPolyList,t)},labelIncompleteNode:function(t,e){var n=this.ptLocator.locate(t.getCoordinate(),this.arg[e].getGeometry());t.getLabel().setLocation(e,n)},copyPoints:function(t){for(var e=this.arg[t].getNodeIterator();e.hasNext();){var n=e.next(),i=this.graph.addNode(n.getCoordinate());i.setLabel(t,n.getLabel().getLocation(t))}},findResultAreaEdges:function(t){for(var e=this.graph.getEdgeEnds().iterator();e.hasNext();){var n=e.next(),i=n.getLabel();i.isArea()&&!n.isInteriorAreaEdge()&&ii.isResultOfOp(i.getLocation(0,cn.RIGHT),i.getLocation(1,cn.RIGHT),t)&&n.setInResult(!0)}},computeLabelsFromDepths:function(){for(var t=this.edgeList.iterator();t.hasNext();){var e=t.next(),n=e.getLabel(),i=e.getDepth();if(!i.isNull()){i.normalize();for(var r=0;2>r;r++)n.isNull(r)||!n.isArea()||i.isNull(r)||(0===i.getDelta(r)?n.toLine(r):(f.isT

TypeError: this.seg.p1.equals2D is not a function
    at Ee.e.findSegmentIndexToSnap (node_modules/jsts/dist/jsts.min.js:11:3859)
    at Ee.e.snapSegments (node_modules/jsts/dist/jsts.min.js:11:3630)
    at Ee.e.snapTo (node_modules/jsts/dist/jsts.min.js:11:3420)
    at Ne.e.snapLine (node_modules/jsts/dist/jsts.min.js:11:5855)
    at Ne.e.transformCoordinates (node_modules/jsts/dist/jsts.min.js:11:5936)
    at Ne.e.transformLinearRing (node_modules/jsts/dist/jsts.min.js:11:2675)
    at Ne.e.transformPolygon (node_modules/jsts/dist/jsts.min.js:11:317)
    at Ne.e.transformMultiPolygon (node_modules/jsts/dist/jsts.min.js:11:1550)
    at Ne.e.transform (node_modules/jsts/dist/jsts.min.js:11:2467)
    at Ie.e.snapTo (node_modules/jsts/dist/jsts.min.js:11:4326)
```

Any hints as to what the issue is here? Thanks.

**Comment by sweco-sebhar** [comment]
Thanks, I think the cause is the same as in #273.

**Comment by bjornharrtell** [comment]
Thanks, I think the cause is the same as in #273.
