### ISSUE TITLE
Cannot read property 'getSRID' of undefined

### ISSUE THREAD

**Issue by erelsgl** [bjornharrtell/jsts#282]
Two years ago, I wrote a simple class that represents an axis-parallel rectangle. I wrote it like this:

```
  jsts.geom.AxisParallelRectangle = function(minx,miny, maxx,maxy, factory) {
	  this.minx = Math.min(minx,maxx);
	  this.miny = Math.min(miny,maxy);
	  this.maxx = Math.max(minx,maxx);
	  this.maxy = Math.max(miny,maxy);
	  this.factory = factory;
  };

  jsts.geom.AxisParallelRectangle.prototype = new jsts.geom.Geometry();   // *** line 29
  jsts.geom.AxisParallelRectangle.constructor = jsts.geom.AxisParallelRectangle;

  jsts.geom.AxisParallelRectangle.prototype.isEmpty = function() {
    return (this.minx==this.maxx || this.miny==this.maxy);
  };

  ...

```

It worked fine with JSTS version 0.14.0

But, with the current version of JSTS (1.2.1), I get this error message on the line marked with "***":
```
TypeError: Cannot read property 'getSRID' of undefined
    at new B (/home/erelsgl/git/computational-geometry/node_modules/jsts/dist/jsts.min.js:6:4047)
    at /home/erelsgl/git/computational-geometry/lib/AxisParallelRectangle.js:29:47
```

How can I make this work with the new version?

**Comment by bjornharrtell** [comment]
The problem is that Geometry constructor is not intended to be called. Could you try replacing `new jsts.geom.Geometry()` with `Object.create(Geometry.prototype)`?

**Comment by erelsgl** [comment]
This works, thanks!
