### ISSUE TITLE
this._ring.isValid is not a function

### ISSUE THREAD

**Issue by bjornharrtell** [bjornharrtell/jsts#388]
TypeError: this._ring.isValid is not a function
      at EdgeRing.isValid (node_modules/jsts/org/locationtech/jts/operation/polygonize/EdgeRing.js:85:21)
      at Polygonizer.findValidRings (node_modules/jsts/org/locationtech/jts/operation/polygonize/Polygonizer.js:77:11)
      at Polygonizer.polygonize (node_modules/jsts/org/locationtech/jts/operation/polygonize/Polygonizer.js:90:9)
      at Polygonizer.getPolygons (node_modules/jsts/org/locationtech/jts/operation/polygonize/Polygonizer.js:113:8)

**Comment by bjornharrtell** [comment]
Fixed in master by https://github.com/bjornharrtell/jsts/commit/f4e6b9ac4d20a987fa3cf44e092e934c80e6a642#diff-8dffacec32a9d6ab706d6341ec47e710
