### ISSUE TITLE
TypeError: this.array.values is not a function when calling buffer on collection

### ISSUE THREAD

**Issue by Krho** [bjornharrtell/jsts#414]
Hi !

The following code

`const wktReader = new jsts.io.WKTReader();`
`const wkt = "GEOMETRYCOLLECTION ("POLYGON ((929464.61 6574944.91, 929464.86 6574947.11, 929466.77 6574960.5, 929469.11 6574967.8, 929469.53` `6574968.52, 929473.14 6574967.11, 929514.66 6574950.92, 929514.19 6574950.07, 929502.7 6574929.15, 929464.61` `6574944.91)),POLYGON ((929464.44 6574943.48, 929464.61 6574944.91, 929502.7 6574929.15, 929464.44 6574943.48)),POLYGON ((929464.0190200877 6574940.014871169, 929464.4436511227 6574943.475951197, 929502.7021457119` `6574929.150352478, 929499.4081529963 6574923.458372557, 929464.0190200877 6574940.014871169)))";`
`const collection = wktReader.read(wkt);`
`const buffer = collection.buffer(0);`

raises exception : 

> TypeError: this.array.values is not a function

    at S.c (myProject/node_modules/jsts/src/java/util/ArrayList.js:82:23)
    at S.addAll (myProject/node_modules/jsts/src/java/util/ArrayList.js:36:21)
    at new S (myProject/node_modules/jsts/src/java/util/ArrayList.js:14:39)
    at Os.createParentBoundables (myProject/node_modules/jsts/src/org/locationtech/jts/index/strtree/STRtree.js:159:35)
    at Os.createHigherLevels (myProject/node_modules/jsts/src/org/locationtech/jts/index/strtree/AbstractSTRtree.js:230:35)
    at Os.build (myProject/node_modules/jsts/src/org/locationtech/jts/index/strtree/AbstractSTRtree.js:186:77)
    at Os.call (myProject/node_modules/jsts/src/org/locationtech/jts/index/strtree/AbstractSTRtree.js:164:12)
    at Os.query (myProject/node_modules/jsts/src/org/locationtech/jts/index/strtree/STRtree.js:131:26)
    at Js.intersectChains (myProject/node_modules/jsts/src/org/locationtech/jts/noding/MCIndexNoder.js:52:41)
    at Js.computeNodes (myProject/node_modules/jsts/src/org/locationtech/jts/noding/MCIndexNoder.js:46:10)
    at Ri.computeNodedEdges (myProject/node_modules/jsts/src/org/locationtech/jts/operation/buffer/BufferBuilder.js:134:11)
    at Ri.buffer (myProject/node_modules/jsts/src/org/locationtech/jts/operation/buffer/BufferBuilder.js:119:10)
    at Fi.bufferOriginalPrecision (myProject/node_modules/jsts/src/org/locationtech/jts/operation/buffer/BufferOp.js:106:41)
    at Fi.computeGeometry (myProject/node_modules/jsts/src/org/locationtech/jts/operation/buffer/BufferOp.js:95:10)
    at Fi.getResultGeometry (myProject/node_modules/jsts/src/org/locationtech/jts/operation/buffer/BufferOp.js:115:10)
    at Function.bufferOp (myProject/node_modules/jsts/src/org/locationtech/jts/operation/buffer/BufferOp.js:33:28)
    at ot.buffer (myProject/node_modules/jsts/src/org/locationtech/jts/monkey.js:76:21)
    at Object.<anonymous> (myProject/tests/myFile.js:14:31)

There is no problem when using releases 2.2.3 and older and JTS TestBuilder works fine with this case. I have other issues that also appeared when using 2.3 release, I can provide them or wait to see if the correction for this works for the others as well.

**Comment by bjornharrtell** [comment]
I can't reproduce. Passing test case added in https://github.com/bjornharrtell/jsts/commit/1240bcab6b91a0b5e8dcaf063e2c276b229350f9 and as far as I can see it works without issues. Feel free to reopen if you can prove me wrong.

PS. I had to clean up your snippet above to make the code/WKT parsable - you have an extra " in the WKT string.
