### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by motto76** [bjornharrtell/jsts#484]
Hello, 

we have a problem with equalsNorm().

In the following test case: 
```
it('check multipolygon and polygon', () => {
  const geomA = createGeometry('MULTIPOLYGON (((0 0, 10 0, 10 10, 0 0)), ((15 5, 15 10, 20 10, 20 5, 15 5)))')
  const geomB = erzeugeGeometrie('POLYGON ((0 0, 10 0, 10 10, 0 10, 0 0))')
  const gf = createGeometryFactory(2)
  expect(geomA.equalsNorm(geomB).toBe(false)
})
```
 the following error occurs: 

_TypeError: Cannot read properties of undefined (reading 'length')._
_Stack:_
_at MultiPolygon.call (node_modules/jsts/org/locationtech/jts/geom/GeometryCollection.js:76:67)
      at MultiPolygon.equalsExact (node_modules/jsts/org/locationtech/jts/geom/MultiPolygon.js:27:32)
      at MultiPolygon.apply (node_modules/jsts/org/locationtech/jts/geom/Geometry.js:33:35)
      at MultiPolygon.apply (node_modules/jsts/org/locationtech/jts/geom/GeometryCollection.js:86:32)
      at MultiPolygon.equalsExact (node_modules/jsts/org/locationtech/jts/geom/MultiPolygon.js:29:32)
      at MultiPolygon.equalsNorm (node_modules/jsts/org/locationtech/jts/geom/Geometry.js:46:24)_

If you swap the geometries you get another error:

_RangeError: Maximum call stack size exceeded
        at Function.[Symbol.hasInstance] (<anonymous>)_
_Stack:_
_at LinearRing.equalsExact (node_modules/jsts/org/locationtech/jts/geom/LineString.js:43:72)
      at LinearRing.apply (node_modules/jsts/org/locationtech/jts/geom/Geometry.js:33:35)
      at LinearRing.equalsExact (node_modules/jsts/org/locationtech/jts/geom/LineString.js:59:32)
      at LinearRing.apply (node_modules/jsts/org/locationtech/jts/geom/Geometry.js:33:35)
      at LinearRing.equalsExact (node_modules/jsts/org/locationtech/jts/geom/LineString.js:59:32)
      at LinearRing.apply (node_modules/jsts/org/locationtech/jts/geom/Geometry.js:33:35)
      at LinearRing.equalsExact (node_modules/jsts/org/locationtech/jts/geom/LineString.js:59:32)
..._

Cause for case 1:
The check in MultiPolygon if (!this.isEquivalentClass(other)) returns true, because the call getClass() returns [class Geometry] for both geometries. (#getClass is implemented only in Geometry and therefore returns 

possible Solution: Each geometry class implements getClass
Alternative: Instead of getClass, getGeometryType is checked.

**Comment by bjornharrtell** [comment]
This regressed in version 2.2.2 due to commit https://github.com/bjornharrtell/jsts/commit/fb3c89b8bb2339ce6692c795e41a957fa17f19f9 back in 2017. I guess it's not that common that people try and compare different geometry types.

**Comment by bjornharrtell** [comment]
I believe this is fixed now and released as 2.9.3

**Comment by motto76** [comment]
Thanks for the quick troubleshooting. We have tested it successfully.
